routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Tienda;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [Tienda::class, 'index']);



Route::resource('tienda', 'Tienda');

app/Model_Tienda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Model_Tienda extends Model
{
    //
    protected $table = 'tiendas';
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Tienda.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model_Tienda;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Crypt;
use League\Flysystem\Filesystem as File;

class Tienda extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $all = Model_Tienda::all();
     
        // var_dump($all);
        return view('list-tiendas',compact('all'))
                     ->with('title', 'Directorio de Tiendas');  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        // $all->title     = "Registro de Tiendas";
        return view('registro-tienda')
        ->with('title', 'Registro de Tiendas');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $tienda=new Model_Tienda;
        $this->validate($request,[ 
            'nombre_tienda'=>'required', 'ubicacion_tienda'=>'required', 
            'telefono_tienda'=>'required', 'email_tienda'=>'required']);
            
        $tienda->nombre_tienda=$request->nombre_tienda;
        $tienda->ubicacion_tienda =$request->ubicacion_tienda;
        $tienda->telefono_tienda=$request->telefono_tienda;
        $tienda->email_tienda =$request->email_tienda;
        // $tienda->ubicacion_tienda =$request->email_user;
        if ($request->hasFile('img_tienda')) {
            $file = $request->file("img_tienda");
          
            $extension = $request->file('img_tienda')->extension();
    
            $name_img = str_replace(' ','_',$tienda->nombre_tienda);
            $safeName =  $file->getClientOriginalName();
        
            Storage::disk('img')->putFileAs('', $file,$name_img.'.'. $extension);
            $tienda->img_url =   $name_img.'.'. $extension ;
           
        }

      
     
        $tienda->save();

        // 
        // Libro::create($request->all());
        // return redirect()->route('libro.index')->with('success','Registro creado satisfactoriamente');
        return redirect()->route('tienda.index')->with('success','Registro creado satisfactoriamente'); 


          
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $id =  Crypt::decrypt($id);
        // var_dump($id);
        $tienda=Model_Tienda::find($id);
        return view('edit-tienda',compact('tienda'))
        ->with('title', 'Edicion de Tienda');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[ 
            'nombre_tienda'=>'required', 'ubicacion_tienda'=>'required', 
            'telefono_tienda'=>'required', 'email_tienda'=>'required']);
            $tienda = Model_Tienda::find($id);
            // $folderName = public_path().'/file/img';
            if(   Storage::disk('img')->exists($tienda->img_url)){
                Storage::disk('img')->delete($tienda->img_url);
            }
            $tienda->nombre_tienda=$request->nombre_tienda;
            $tienda->ubicacion_tienda =$request->ubicacion_tienda;
            $tienda->telefono_tienda=$request->telefono_tienda;
            $tienda->email_tienda =$request->email_tienda;
            if ($request->hasFile('img_tienda')) {
                $file = $request->file("img_tienda");
                $extension = $request->file('img_tienda')->extension();
                $name_img = str_replace(' ','_',$tienda->nombre_tienda);
                $safeName =  $file->getClientOriginalName();
                Storage::disk('img')->putFileAs('', $file,$name_img.'.'. $extension);
                $tienda->img_url =   $name_img.'.'. $extension ;
               
            }
          
         
            $tienda->save();
            return redirect()->route('tienda.index')->with('success','Tienda actualizada satisfactoriamente');
     
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Model_Tienda::find($id)->delete();
        return redirect()->route('tienda.index')->with('success','Registro eliminado satisfactoriamente');
    }
}

resources/views/edit-tienda.blade.php
@extends('welcome')
@section('content')
@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
<form action="{{ route('tienda.update',$tienda->id) }}"  role="form" method="post" enctype="multipart/form-data" class="mt-3 p-2">
{{ csrf_field() }}
<input name="_method" type="hidden" value="PATCH">
    <div class="form-group">
      <div class="row">
          <div class="mb-3 col-5">
            <label for="formFileSm" class="form-label">Nombre</label>
            <input class="form-control" type="text" id="formFile" name="nombre_tienda"  value="{{$tienda->nombre_tienda}}">
          </div>
          <div class="mb-3 col-5">
            <label for="formFileSm" class="form-label">Ubicacion</label>
            <input class="form-control" type="text" id="formFileMultiple" name="ubicacion_tienda" value="{{$tienda->ubicacion_tienda}}">
          </div>
          <div class="mb-3 col-5">
            <label for="formFileSm" class="form-label">Telefono</label>
            <input class="form-control" type="text" id="formFileDisabled" name="telefono_tienda"  value="{{$tienda->telefono_tienda}}">
          </div>
          <div class="mb-3 col-5">
            <label for="formFileSm" class="form-label">Email</label>
            <input class="form-control form-control-sm" id="formFileSm" type="email" name="email_tienda" value="{{$tienda->email_tienda}}">
          </div>
          <div class="mb-3 col-5">
            <!-- <label for="formFileSm" class="form-label">Img Actual</label> -->
            <img class="card-img-top m-auto" src="{{ asset('file/img/'.$tienda->img_url) }}" alt="Card image cap">
          </div>
          <div class="mb-3 col-5">
            <label for="formFileSm" class="form-label">Img</label>
            <input class="form-control form-control-sm" id="formFileSm" type="file" name="img_tienda">
          </div>
          <div class="mb-3">
          <button type="submit" class="btn btn-success">Send</button>
          </form>
          <a href="{{ route('tienda.index') }}"> 
          <button type="button" class="btn btn-secondary">Atras</button>
          </a>
          </div>
         
      </div>
    </div>

@endsection

resources/views/list-tiendas.blade.php
@extends('welcome')

@section('content')
<div class="menu-tienda">
    @include('menu')
</div>
        <!--  -->
<div class="row">
@if(Session::has('success'))
			<div class="alert alert-info m-2 mb-0">
				{{Session::get('success')}}
			</div>
			@endif
@if($all->count())  
              @foreach($all as $tienda)  
    <div class="col-4 mt-5">
        <div class="card" style="width: 25rem;">
        <div class="card-header text-center">
           <img class="card-img-top m-auto"   src="{{ asset('file/img/'.$tienda->img_url) }}">
           <!-- src=" {{asset($tienda->img_url) }}" -->
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ ucfirst(trans($tienda->nombre_tienda)) }}</h5>
          <ul class="list-group list-group-flush">
          <li class="list-group-item m-0 p-0"></li>
            <li class="list-group-item"><i class="bi bi-geo-alt"></i> {{$tienda->ubicacion_tienda}}</li>
            <li class="list-group-item"><i class="bi bi-telephone"></i> {{$tienda->telefono_tienda}}</li>
            <li class="list-group-item"><i class="bi bi-at"></i>{{$tienda->email_tienda}}</li>
            <li class="list-group-item text-center">
                <div class="btn-group" role="group" aria-label="Basic outlined example">
       
                <!-- <a href="{{ route('tienda.destroy',$tienda->id) }}">  -->
                <form action="{{action('Tienda@destroy', $tienda->id)}}"  role="form" method="post" class="m-0 p-0">
                @csrf
             @method('DELETE')
                  <button type="submit" class="btn btn-danger"><i class="bi bi-trash"></i></button>
                </form>
                <!-- </a> -->
                 <a href="{{action('Tienda@edit', Crypt::encrypt( $tienda->id))}}"> 
                    <button type="button" class="btn btn-success"><i class="bi bi-pencil"></i></button>
                    </a>
                </div>
            </li>
          </ul>
          <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
        </div>
        </div>
    </div>
 
@endforeach 
</div>
               @else
               <div class="m-2 p-2">    <h3>No hay tiendas registradas</h3></div>
              @endif
 @endsection

        

      

resources/views/menu.blade.php
<style>
    .btn-outline-primary{
        /* color:#fff !important; */
        /* border:#fff !important; */
        font-size: 20px;
    }
</style>

<div class="btn-group" role="group" aria-label="Basic outlined example">
<a href="{{ route('tienda.create') }}">  <button type="button"  class="btn btn-primary"> Registrar</button>
</a>
</div>

resources/views/registro-tienda.blade.php
@extends('welcome')
@section('content')
@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
<form action="{{ route('tienda.store') }}"  role="form" method="post" enctype="multipart/form-data" class="mt-3 p-2">
{{ csrf_field() }}
    <div class="form-group">
      <div class="row">
          <div class="mb-3 col-5">
            <label for="formFileSm" class="form-label">Nombre</label>
            <input class="form-control" type="text" id="formFile" name="nombre_tienda">
          </div>
          <div class="mb-3 col-5">
            <label for="formFileSm" class="form-label">Ubicacion</label>
            <input class="form-control" type="text" id="formFileMultiple" name="ubicacion_tienda">
          </div>
          <div class="mb-3 col-5">
            <label for="formFileSm" class="form-label">Telefono</label>
            <input class="form-control" type="text" id="formFileDisabled" name="telefono_tienda" >
          </div>
          <div class="mb-3 col-5">
            <label for="formFileSm" class="form-label">Email</label>
            <input class="form-control form-control-sm" id="formFileSm" type="email" name="email_tienda">
          </div>
          <div class="mb-3 col-5">
            <label for="formFileSm" class="form-label">Img</label>
            <input class="form-control form-control-sm" id="formFileSm" type="file" name="img_tienda">
          </div>
          <div class="mb-3">
          <button type="submit" class="btn btn-success">Send</button>
          </form>
          <a href="{{ route('tienda.index') }}"> 
          <button type="button" class="btn btn-secondary">Atras</button>
          </a>
          </div>
         
      </div>
    </div>

@endsection